name: epytodo_sender

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MIRROR_URL: 'git@github.com:EpitechPromo2028/B-WEB-200-MPL-2-1-epytodo-brahim.benali.git'

jobs:
    Send_to_repisitory:
        timeout-minutes: 4
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            with:
              fetch-depth: 0
          - uses: pixta-dev/repository-mirroring-action@v1
            with:
              target_repo_url: ${{env.MIRROR_URL}}
              ssh_private_key: ${{secrets.SSH_PRIVATE_KEY}}